<?php

namespace Coopernet\QuizBundle\Repository;

/**
 * AnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerRepository extends \Doctrine\ORM\EntityRepository {
  public function getAnswersWithSpecificTitle(array $answerTitles) {
    $qb = $this
      ->createQueryBuilder('a');

    // Puis on filtre sur le titre des questions à l'aide d'un IN
    $qb->where($qb->expr()->in('a.title', $answerTitles));
    // La syntaxe du IN et d'autres expressions se trouve dans la documentation Doctrine

    // Enfin, on retourne le résultat
    return $qb
      ->getQuery()
      ->getResult();
  }
}
