<?php

namespace Coopernet\QuizBundle\Repository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends \Doctrine\ORM\EntityRepository {
  public function getQuestionsWithSpecificTitle(array $questionTitles) {
    $qb = $this
      ->createQueryBuilder('q');

    // Puis on filtre sur le titre des questions à l'aide d'un IN
    $qb->where($qb->expr()->in('q.title', $questionTitles));
    // La syntaxe du IN et d'autres expressions se trouve dans la documentation Doctrine

    // Enfin, on retourne le résultat
    return $qb
      ->getQuery()
      ->getResult();
  }
  public function getAllQFromSpecficQuiz($quiz_id) {
    $query = $this
      ->createQueryBuilder('question')
      ->leftJoin('question.questions', 'questionanswer')
      ->addSelect('questionanswer')
      ->leftJoin('questionanswer.answer', 'answer')
      ->leftJoin('question.quizs','quizs')
      ->where('quizs.id = :quiz_id')
      ->addSelect('quizs')
      ->orderBy('question.title', 'ASC');

    $query->setParameter('quiz_id', $quiz_id);

    return $query
      ->getQuery()
      ->getResult();
  }
}
