<?php

namespace Coopernet\QuizBundle\Repository;

/**
 * QuestionAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionAnswerRepository extends \Doctrine\ORM\EntityRepository {
  public function getAllQAFromSpecficQuiz($quiz_id) {
    $query = $this
      ->createQueryBuilder('qa')
      ->leftJoin('qa.answer', 'answer')
      ->addSelect('answer')
      ->leftJoin('qa.question', 'question')
      ->leftJoin('question.quizs','quizs')
      ->where('quizs.id = :quiz_id')
      ->addSelect('question')
      ->addSelect('quizs')
      ->orderBy('question.title', 'ASC');

    $query->setParameter('quiz_id', $quiz_id);

    return $query
      ->getQuery()
      ->getResult();
  }
  public function getAllAnswerFromQuestion($question_id) {
    $query = $this
      ->createQueryBuilder('qa')
      ->leftJoin('qa.answer', 'answer')
      ->addSelect('answer')
      ->where('qa.question = :question_id');

    $query->setParameter('question_id', $question_id);

    return $query
      ->getQuery()
      ->getResult();
  }

}
