<?php

namespace Coopernet\QuizBundle\Repository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends \Doctrine\ORM\EntityRepository {
  public function getQuestionsWithSpecificTitle(array $questionTitles) {
    $qb = $this
      ->createQueryBuilder('q');

    // Puis on filtre sur le titre des questions à l'aide d'un IN
    $qb->where($qb->expr()->in('q.title', $questionTitles));
    // La syntaxe du IN et d'autres expressions se trouve dans la documentation Doctrine

    // Enfin, on retourne le résultat
    return $qb
      ->getQuery()
      ->getResult();
  }
}
