<?php

namespace Coopernet\QuizBundle\Repository;

/**
 * QuizRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizRepository extends \Doctrine\ORM\EntityRepository
{
  public function getQuizWithSpecificName(array $quizNames) {
    $qb = $this
      ->createQueryBuilder('q')
    ;

    // Puis on filtre sur le nom des quiz à l'aide d'un IN
    $qb->where($qb->expr()->in('q.name', $quizNames));
    // La syntaxe du IN et d'autres expressions se trouve dans la documentation Doctrine

    // Enfin, on retourne le résultat
    return $qb
      ->getQuery()
      ->getResult()
      ;
  }
}
